export const products = [
    {
        id: 1,
        tag: "iphone",
        gia: 7990000,
        giaGoc: 9990000,
        hinh: "../image/iphone-12-tím.jpg",
        ten: "iPhone 12 chính hãng VN/A(Full VAT)(128GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 2,
        tag: "iphone",
        gia: 14990000,
        giaGoc: 19990000,
        hinh: "../image/iphone-12-pro-max.jpg",
        ten: "iPhone 12 Pro chính hãng VN/A(Full VAT)(128GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 3,
        tag: "iphone",
        gia: 2790000,
        giaGoc: 29990000,
        hinh: "../image/iphone-12-pro-gold-vna-00-700x700.jpg",
        ten: "iPhone 12 Pro Max VN/A(Full VAT)(128GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 4,
        tag: "ipad",
        gia: 19990000,
        giaGoc: 2590000,
        hinh: "../image/ipad-2020-gray-00-700x700.jpg",
        ten: "iPad Gen 8 chính hãng VN/A(Full VAT)(512GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 5,
        tag: "ipad",
        gia: 16990000,
        giaGoc: 18990000,
        hinh: "../image/ipad-air-2020-blue-wifi-00-700x700.jpg",
        ten: "iPad Air 4 chính hãng VN/A(Full VAT)(512GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 6,
        tag: "ipad",
        gia: 20990000,
        giaGoc: 22990000,
        hinh: "../image/ipad-pro-11-wifi-space-gray-2020-700x700.jpg",
        ten: "iPad Pro 2020 chính hãng VN/A(Full VAT)(512GB)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 7,
        tag: "mac",
        gia: 17990000,
        giaGoc: 19990000,
        hinh: "../image/macbook-air-2018-gold-00-700x700.jpg",
        ten: "MacBook Air 2018 chính hãng VN/A(Full VAT)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 8,
        tag: "mac",
        gia: 24990000,
        giaGoc: 26990000,
        hinh: "../image/macbook-air-2020-chip-m1-gray-00-700x700.jpg",
        ten: "MacBook Air 2020 chính hãng VN/A(Full VAT)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
    {
        id: 9,
        tag: "mac",
        gia: 39990000,
        giaGoc: 41990000,
        hinh: "../image/macbook-pro-2020-13-inch-chip-m1-gray-00-700x700.jpg",
        ten: "MacBook Pro 2020 chính hãng VN/A(Full VAT)",
        soluong: 0,
        manHinh: "RETINA, 6.2, Full HD+",
        heDieuHanh: "IOS",
        thuongHieu: "Apple",
        cameraTruoc: "20 MP",
        cameraSau: "12 MP ",
        ram: "6 GB",
        rom: "64 GB"
    },
]